### ISSUE TITLE
Make it support strings

### ISSUE THREAD

**Issue by johann-petrak** [pinterest/pymemcache#227]
Just doing `client.set("k1", "vü")`  results in an exception:

```
~/software/anaconda3/lib/python3.6/site-packages/pymemcache/client/base.py in _store_cmd(self, name, values, expire, noreply, cas)
    820                     data = six.text_type(data).encode('ascii')
    821                 except UnicodeEncodeError as e:
--> 822                     raise MemcacheIllegalInputError(str(e))
    823 
    824             cmds.append(name + b' ' + key + b' ' +

MemcacheIllegalInputError: 'ascii' codec can't encode character '\xfc' in position 1: ordinal not in range(128)
```

**Comment by jparise** [comment]
Memcache itself stores bytes so it's the caller's responsibility to handle string encoding. In order to handle string encoding automatically in pymemcache, we'd need to add an `encoding` option so that we'd know how to decode the bytes back to the original format.

My preference is to _not_ go that route and instead have callers handle string encoding / decoding themselves, which is explicit and non-magical.

**Comment by jparise** [comment]
I improved the exception message to hopefully make this clearer.
