### ISSUE TITLE
pymemcache.exceptions.MemcacheUnknownError

### ISSUE THREAD

**Issue by caspii** [pinterest/pymemcache#231]
I'm seeing the following exception after migrating my webapp from Ubuntu 14.04 to 18.04 and from python 2.7 to 3.6.

Any ideas?

```

File "/var/www/keepthescore.co/venv/lib/python3.6/site-packages/pymemcache/client/base.py", line 450, in get
    return self._fetch_cmd(b'get', [key], False).get(key, default)
  File "/var/www/keepthescore.co/venv/lib/python3.6/site-packages/pymemcache/client/base.py", line 790, in _fetch_cmd
    raise MemcacheUnknownError(line[:32])
pymemcache.exceptions.MemcacheUnknownError: b'ay, 5/3 - Every grade had over 8'
```

**Comment by cgordon** [comment]
I took a look at the code, and that error is telling us that the client read a line from the socket that it could not parse. The first 32 characters of the line are printed in the output, and it looks like part of either a key or value from memcache (or maybe some other data entirely?).

My best guess, without knowing a lot more about your application, is that this is a concurrency error, and there is more than one thread using the same memcache client. Maybe something else changed with the upgrade to python 3.6, or this was a latent bug that was triggered by that upgrade? In either case, I'd need to understand more about the concurrency in your application to be able to help more than that.

**Comment by caspii** [comment]
Thanks for the quick reply!

Unfortunately I'm a noob when it comes to threading. I can tell you that it's a Flask app with this in the main method:

```
app.run(threaded=True)
```

I use Apache to serve the app.

**Comment by cgordon** [comment]
It has been a lot of years since I used Flask, and I've never used it with threads. I would start by confirming that threading is actually the issue. It looks like it may be possible to just set `threaded=False` in that constructor. That probably won't lead to a very high performance server, but it may make it possible to confirm the problem. If you find that it is not a problem related to threading, then I can probably help, but otherwise I don't think I'll be able to do much for you.

**Comment by caspii** [comment]
Ok. I'll give it a try. Thanks

**Comment by jparise** [comment]
Closing this because there hasn't been any activity in many months. Please reopen if new information comes up.

**Comment by roxanebellot** [comment]
Hi.

I happened to bump in a similar case.
We don't use Flask but Django (4.2) with [PyMemcacheCache cache backend](https://docs.djangoproject.com/fr/4.2/topics/cache/#memcached). Each day, we have about a thousand celery tasks that use the cache. About 5 per day end up with a MemcacheUnknownError. I haven't yet found how to replicate issue.

Since my key has more than 32 characters, the error has no useful information. Could this limit be expended, to display all the line, or let's say the 200 first characters, to gain access to data on what is happening here ?
