### ISSUE TITLE
practical issue: Identifying keys to delete

### ISSUE THREAD

**Issue by transfluxus** [pinterest/pymemcache#299]
Hello,

I am searching search queries in my application. These queries are composed dicts and are hashed to generate keys for caching.
However every now and then I need to delete them, cuz I know what they return is invalid. However, how can I identify all those keys. I considered the opportunity for namespaces, but I am missing a function that returns all existing keys in the cache.

any tips appreciated

**Comment by jparise** [comment]
@transfluxus You might find some of the answers here useful: https://stackoverflow.com/questions/19560150/get-all-keys-set-in-memcached

pymemcache itself doesn't provide a way to retrieve all of the keys in the memcached server because there isn't a way to do that in the [official memcached protocol](https://github.com/memcached/memcached/blob/master/doc/protocol.txt).
