### ISSUE TITLE
Compatability break with IPv6 changes in 3.4 release

### ISSUE THREAD

**Issue by rsyring** [pinterest/pymemcache#301]
Running with Python 3.8.7 on Ubuntu 18.04.5 LTS, pymemcache 3.3.0 would connect to IP `127.0.0.1` if the server was "localhost."  As of pymemcache 3.4, "localhost" is resolved to `::1`.  For our servers, where we block IPv6 traffic, this broke our connections.

Mostly just documenting the issue here.  Maybe changelog/docs could address the change?

Thanks.

**Comment by jparise** [comment]
This behavior change was probably introduced due to #296, although I _think_ it occurs based on the local machine's resolver preferring to return the IPv6 address (`::1`) before the IPv4 address (`127.0.0.1`) when it resolves `localhost`. The pymemcache code itself doesn't express an explicit preference for IPv6 addresses over IPv4; it takes the addresses in the order in which they're returned by [`socket.getaddrinfo()`](https://docs.python.org/3.9/library/socket.html#socket.getaddrinfo).

For an environment like yours, where IPv6 addresses are blocked, is it common for the resolver to still return IPv6 addresses for hostnames? I'd thinking through how to best phrase a documentation update for this behavior.

**Comment by jparise** [comment]
I just took a look at current docs (shipped with version 3.4.0), and it seems like this is already called out: https://github.com/pinterest/pymemcache/blob/9bf5dd5d6e4bf2d6de9d3b2778e55958a74474a9/docs/getting_started.rst#L37-L38

I'll retroactively update the 3.4.0 changelog entry to highlight this though.
