### ISSUE TITLE
Implementing a reconnection logic after MemcacheUnexpectedCloseError

### ISSUE THREAD

**Issue by cayolblake** [pinterest/pymemcache#307]
In the occasion of a memcached server restart, on the first access attempt after server restarted, we get "MemcacheUnexpectedCloseError" and the request fails, then the next following access (a totally different request) goes through properly.

What am I missing here? Do I need to implement some reconnection logic on failure? Any hints on doing so if that's the case?

**Comment by cayolblake** [comment]
Well, after a connection breaks, contrary to what you stated, it doesn't attempt to reconnect on its own, and that's my main issue.

**Comment by cgordon** [comment]
> In the occasion of a memcached server restart, on the first access attempt after server restarted, we get "MemcacheUnexpectedCloseError" and the request fails, then the next following access (a totally different request) goes through properly.

As you noted, "the next following access [..] goes through properly". That is pymemcache re-establishing the connection automatically for you.

**Comment by cayolblake** [comment]
I'll try to clarify a bit more.

1. Operation is normal.
2. Memcached server restarts.
3. First operation after restart fails with "MemcacheUnexpectedCloseError". It fails.
4. Second operation goes fine.

My expectation is on step 3 it reconnects and let the operation go through taking into consideration the overhead of the reconnection.

**Comment by cgordon** [comment]
I will also try to clarify more.

There are many ways to use memcached, and there is no one-size-fits-all error handling solution that will work for everyone. Because of that, pymemcache reports errors to users, and expects users to handle those errors appropriately for their use case. As a convenience, if you continue to make requests through the pymemcache Client, it will attempt to reconnect a closed socket for you. That just saves you the trouble of needing to create a new Client instance, or call an explicit "reconnect" API. The automatic retries are not designed to paper over issues connecting to memcached. I believe that explicit errors are the best way for this API to communicate with its users when an issue occurs.

In my opinion, it would be a bad idea for pymemcache to add automatic retries into the core Client library. I strongly prefer that users of the library see exceptions rather than high latency (as would happen with a retry/backoff loop). I tried to outline some of the possible ways that errors can be handled in my long post above. The error case you mentioned is a good candidate for automatic retries, but it is not the only kind of error experienced by memcached users (and it is very unlikely to be the only kind of error you experience, particularly if your request rate increases over time).

If you want automatic retries then it would be relatively easy to add a configurable Client wrapper that automatically retried requests. We would be happy to review that as a submission if you are so inclined.

**Comment by 4383** [comment]
Hello,

We face similar issue in Openstack.

We think that retry mechanisms on the pymemcache can help to solve this kind of problem.

Indeed on Openstack we recently introduced a cache backend [1] based pymemcache through the dogpile.cache lib [2].

Sometime servers need to be restarted (maintenance, network issues, etc...) and that lead us to similar scenario.

As we are few customers facing the same issue, maybe the solution could be to implement a centralized scenario, based on  optional retry conveniences on the lib side. Without modifying the default behaviour we could pass an option to indicate that we want retry when `MemcacheUnexpectedCloseError` are thrown. That would provide to the community of pymemcache a standardized way to handle such errors.

What if the wrapper is internal to pymemcache?

What if the errors management is standardized and uniformed?

What if pymemcache users design their failing strategy by passing option?

If we standardize and design retry strategies that cover of 20% of the possible server problems and who lead to 80% of the issues faced by users, then, it will only remaining the exotic use cases. As you said these exotic cases could remains under the responsibility of the users. I guess that the major part of users will be happy with the 20% of proposed strategies.

Thoughts?

[1] https://opendev.org/openstack/oslo.cache/commit/b00b3b23b42652dc7e9af8ec54a7f117b6999895
[2] https://github.com/sqlalchemy/dogpile.cache/commit/a2e25bc743a48d91705d944e52aa667ebff10943

**Comment by cayolblake** [comment]
Interesting, I honestly gave up after reading the last clearly-rejecting and pushy reply without even understanding the issue.

Disappointedly, I guess I have to join the Openstack team to be able to report an issue and get traction.

@4383 thanks in due.

**Comment by cgordon** [comment]
@4383

I don't want the core `Client` library to be opinionated about how errors are handled, and I've tried to explain why in my previous comments in this issue. That means I generally want users to build their own error handling strategies. The "right way" to make your own error handling strategy is by writing a small wrapper class that has the same API as the `Client` class. For example, you could write a `RetryingClient` class that delegates calls to an underlying `Client` and does retries when it sees `MemcacheUnexpectedClose`. If you have it take a client object as an argument you could even do cool things like `rc = RetryingClient(Client(...), ...)`, or `rc = HashClient(Client(...), ...)`, so users of either `Client` or `HashClient` could use your wrapper.

If you build such a wrapper and test it, I would love to include it in `pymemcache` along side the `PooledClient` and `HashClient` libraries that were contributed by other users. Take a look at those two classes for examples of how to build a wrapper, and please send a PR if you end up taking this approach.

Having said that, I would like to have one more try at convincing you that a simple retry strategy may not be what you want. If a memcached server goes down for a while (say, five minutes), then a retry strategy is going to cause *all* of your requests to be hung waiting for that server for potentially a long time (depending on your retry policy, the connect_timeout and TCP's retry configuration). Since you are likely using memcached to reduce the latency of your requests and increase your availability, that failure scenario is sub-optimal. You generally don't want a memcached outage to cause a site outage. When possible, I would advocate ignoring memcache exceptions and using a low value for `connect_timeout` and `timeout`. That will increase the load to whatever datastore is behind your memcached instance (when there is an outage), so you also have to watch out for that. The other way a memcached outage causes a bigger outage is by causing too much load to be sent to a backend datastore, so you may also need a way to throttle requests going to your data store. You need that anyway, most of the time, so it shouldn't require any unnecessary work.

Separately, if you're planning to use memcache in a larger deployment, you may want to consider `HashClient`, which will allow you to distribute your data across more servers, both increasing availability and decreasing the load on the individual memcached servers.

**Comment by cgordon** [comment]
@cayolblake

I invested a lot of time trying to explain how `pymemcache` handles errors (and why it does it that way) and I resent being called "pushy" as a result of that effort. I recognize that tone doesn't come across very well on the internet, but I was in no way attempting to reject your issue. I wrote you long comments in an earnest attempt at substantive conversation.

**Comment by 4383** [comment]
@cgordon thank you for your time and thank you for your fully detailed and useful comments.

I'll spend time on your different propositions, and I'll try to back with more updates from our side ASAP.
